### ISSUE TITLE
P32 tinygo flashのflags

### ISSUE THREAD

**Issue by matsujirushi** [sago35/tinygobook#2]
`tinygo flash --target wioterminal --size short examples/blinky1`とあるが、flagsはハイフン1つが正しい？
（ハイフン2つでも機能はしているように見える）

`tinygo flash -target wioterminal -size short examples/blinky1`

**Comment by sago35** [comment]
tinygo コマンドとしてはハイフンは 1 つでも 2つでも OK です。
※Go の flag package を使っていて、 - でも -- でも大丈夫であるため

ただ、 P.118 で `-o` でも `--o` でも良い、と書いていますが、 P.32 時点では書けていないので、
書籍の記述としてはハイフン一つが正しいです。

**Comment by sago35** [comment]
(来週になると思いますが、正誤表の md 作って記載します)
