### ISSUE TITLE
P229 RTL8720DNのファームウェアアップデート

### ISSUE THREAD

**Issue by matsujirushi** [sago35/tinygobook#3]
`ambd_flash_tool.exe flash`だと、RadioのリージョンがJPになっていない可能性が高いです...。
事実確認しますので少々お時間ください。

参考
* [RTL8720DNの最新ファームウェア](https://github.com/Seeed-Studio/seeed-ambd-firmware/releases/tag/v2.1.3)

**Comment by matsujirushi** [comment]
```
git clone https://github.com/Seeed-Studio/ambd_flash_tool
cd ambd_flash_tool
ambd_flash_tool.exe flash
```

で書き込まれるRTL8720DNファームウェアは[20210317-seeed-ambd-firmware-rpc-v2.1.2.zip](https://github.com/Seeed-Studio/seeed-ambd-firmware/releases/tag/v2.1.2)でした。（日本版ではありませんでした。）

参考：[Wio Terminalの新しいRTL8720ファームウェアをリリースしました](https://lab.seeed.co.jp/entry/2020/11/12/120000)

ambd_flash_toolリポジトリに日本語版のブランチを用意しましたので、こちらのコマンドをご案内願います。
（日本語版ファームウェアにアップデートできることは確認済み。書籍記載のコードでは動作確認していないです。）

```
git clone https://github.com/Seeed-Studio/ambd_flash_tool -b JP
cd ambd_flash_tool
ambd_flash_tool.exe flash
```

**Comment by sago35** [comment]
以下で無事に update 出来ました。
少なくとも Windows と Ubuntu22.04 で確認済。
なので、 `-b JP` だけ追加すれば大丈夫そうです。


```
$ git clone https://github.com/Seeed-Studio/ambd_flash_tool --branch JP
$ cd ambd_flash_tool
$ ambd_flash_tool.exe erase
$ ambd_flash_tool.exe flash
```

**Comment by sago35** [comment]
macOS も確認が取れたので、今日の遅い時間？に記載追加します。
Issue 登録ありがとうございました。

**Comment by sago35** [comment]
e8a8c7a555a73bf0608c1167f00eaa2b9c8bbed5 で記載しました。
