### ISSUE TITLE
付録のXIAO RP2040を使用したデバッガーは、「基礎から学ぶ組込みRust」の環境でも使用できますか？

### ISSUE THREAD

**Issue by m1goh** [sago35/tinygobook#4]

**Comment by sago35** [comment]
cmsis-dap なので大丈夫なはずです。
組込み Rust 側？にも聞いてみますね。

**Comment by sago35** [comment]
ということで、大丈夫、とのことです。 @m1goh 

> 書籍執筆時につかってたのはfreedap実装のやつだった気がしますが、rust-dapはWio Terminalでもつかえるのと、probe-runとかも対応してるので、ちゃんと使えますよ。

https://twitter.com/ciniml/status/1599013943120306176?s=20&t=8u92sBX8Pk-qTys9YlzZnw

**Comment by sago35** [comment]
もし、動かない等があれば、 上記 twitter スレッドか、ここにでも書いてください。

**Comment by m1goh** [comment]
@sago35 さん、ありがとうございます。

**Comment by sago35** [comment]
おっと、この Issue の詳細が追加されていましたね。

もし Rust / probe-run とかで使って動かない場合は、 TinyGo 本の接続に追加して 0 番ピンもつないでみてください。
この リポジトリで配布している uf2 ファイルも、リセットは XIAO-RP2040 の 0 番ピンで出力されているので。

接続の詳細は以下に有ります。
https://github.com/ciniml/rust-dap/tree/main/boards/xiao_rp2040

FFC の 4 番ピンが RESET ピンになります。
https://files.seeedstudio.com/wiki/Wio-Terminal/res/Wio-Terminal-SCH-v1.2.pdf
