### ISSUE TITLE
P.33 Hello Wio TerminalがWSL Ubuntu20.04でエラーになります

### ISSUE THREAD

**Issue by m1goh** [sago35/tinygobook#5]
TinyGo本、コマンドが多かったのでWSL Ubuntu20.04の環境で実行していましたがP.33 Hello Wio Terminalで
akiyoshi@LAPTOP-JPBE28JN:~/ledproject$ tinygo flash --target wioterminal
error: failed to flash /tmp/tinygo2745262142/main.uf2: unable to locate device: Arduino
とエラーになりました。

Windowsで実行すると問題なくできました。Linux環境で実行する場合はどうしたらよいでしょうか？教えていただけるとありがたいです、よろしくお願いします。

**Comment by sago35** [comment]
wsl の場合、直接 tinygo flash 出来ないので、 tinygo build してから windows 側で書き込む必要があります。
この時、ブートローダーに入れる必要があるので少し面倒な気配はあります。

以下を組み合わせると少しはましかもしれません。
https://github.com/sago35/touchSerialPortAt1200bps

**Comment by m1goh** [comment]
@sago35 さん、返信ありがとうございます。
Windowsでtinygo flashしてみましたがブートローダーにしてくれて便利だなと思いました。
まだ、よくわからないのでいろいろやってみたいと思います。ありがとうございました。
