### ISSUE TITLE
unsafe.PointerのP.89のサンプルの確認方法

### ISSUE THREAD

**Issue by m1goh** [sago35/tinygobook#6]
P.89のサンプルコードを入力しました。ATSAMD51マイコンのレジスタを参照してSerial Numberを表示してくれると思うのですが？Windows11のパソコンで動かすとこんな感じです。
tinygo build .してみました。
c:\tinygobook\chapter030901>chapter030901.exe
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
ATSAMD51マイコンのレジスタを参照しているのでどうやって確認すればいいのでしょうか？Wio Terminal上で実行すればいいのでしょうか？どうやればいいのか教えて下さい。よろしくお願いします。

**Comment by sago35** [comment]
@m1goh 
P.89 のプログラムはマイコン側で動かす必要があります。
確かにいきなり TinyGo が必要なコードとなるので分かりにくいですね。

P.89 に記載のプログラムを例えば main.go に書き込んで、以下のコマンドで確認できます。
`-monitor` を使う代わりに Tera Term 等を使っていただいても OK です。

```
$ tinygo flash -target wioterminal -monitor .
Connected to COM38. Press Ctrl-C to exit.
B3E43276 53374338 38202020 FF122B3B
B3E43276 53374338 38202020 FF122B3B
B3E43276 53374338 38202020 FF122B3B
```

**Comment by m1goh** [comment]
@sago35 
すいません、お手数をおかけしました。Tera Termで確認できました。
本の前半のTera Termの説明の所をもう一度読んでみればよかったです。ありがとうございました。
